name: "ESLint Testing"

on: [pull_request]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libudev-dev
        run: sudo apt-get install libudev-dev

      - name: Install Dependencies
        run: npm prune

      - name: Run ESLint
        run: npm run test
        continue-on-error: false
